version: '3'
services:
  react-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=www.real-domain-2.com
      - VIRTUAL_PORT=80